name: mpml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13.5
  - fenics-dolfinx=0.9.0
  - mpi4py=4.0.1 # required by fenics
  - pyvista=0.44.2
  - matplotlib=3.10.0
  - numpy=2.2.1
  - scipy=1.15.1