name: mpml
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - fenics-dolfinx=0.9.0
  - mpi4py=4.0.1 # required by fenics
  - pyvista
  - matplotlib
  - numpy
  - scipy
  - pip
  - pip:
      - pychop
      - pandas # required by pychop
      - torch # required by pychop